# Generated by Django 6.1.1 on 2026-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='imagem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
